name: Build the agent container image

on:
  workflow_dispatch:
    inputs:
      acrname:
        description: 'Azure Container Registry Name'
        required: true
        default: ''

jobs:
  createagent:
    name: Create Agent Image and Push to ACR
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker Build
      run: |
        docker build -f agent/Dockerfile -t ${{ github.event.inputs.acrname }}.azurecr.io/agent:$GITHUB_RUN_ID agent/.
        docker tag ${{ github.event.inputs.acrname }}.azurecr.io/agent:$GITHUB_RUN_ID ${{ github.event.inputs.acrname }}.azurecr.io/agent:latest

    - name: Login to ACR
      run: |
        az login --identity
        az acr login --name ${{ github.event.inputs.acrname }}

    - name: Push to ACR
      run: |
        docker push ${{ github.event.inputs.acrname }}.azurecr.io/agent:$GITHUB_RUN_ID
        docker push ${{ github.event.inputs.acrname }}.azurecr.io/agent:latest
        
