name: Build the agent container image

on:
  push:
    branches: [ main ]
    paths:
      - 'agent/Dockerfile'

env:
  ACRNAME: acrfxgj757ivblxk

jobs:
  createagent:
    name: Create Agent Image and Push to ACR
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker Build
      run: |
        docker build -f agent/Dockerfile -t $ACRNAME.azurecr.io/agent:$GITHUB_RUN_ID agent/.
        docker tag $ACRNAME.azurecr.io/agent:$GITHUB_RUN_ID $ACRNAME.azurecr.io/agent:latest

    - name: Login to ACR
      run: |
        az login --identity
        az acr login --name $ACRNAME

    - name: Push to ACR
      run: |
        docker push $ACRNAME.azurecr.io/agent
        
