name: Retrieve Configuration without providing a secret

on:
  workflow_dispatch:
    inputs:
      acrname:
        description: 'Azure Container Registry Name'
        required: true
        default: ''
      kvname:
        description: 'KeyVault Name'
        required: true
        default: ''

jobs:
  init:
    name: Ensure connection to ACR
    runs-on: self-hosted

    steps:
    - name: Login to ACR
      run: |
        az login --identity
        az acr login --name ${{ github.event.inputs.acrname }}

  readfromkeyvault:
    needs: init
    name: Read configuration from KeyVault
    runs-on: self-hosted
    container: ${{ github.event.inputs.acrname }}.azurecr.io/agent:latest
    outputs:
      someconfig: ${{ steps.configuration.outputs.someconfig }}
    steps:
    - name: Login Azure
      run: |
        az login --identity

    - name: Load from KeyVault
      id: configuration
      run: |
        someconfig=$(az keyvault secret show --vault-name ${{ github.event.inputs.kvname }} --name somekey -o tsv --query 'value')
        echo "::set-output name=someconfig::$someconfig"
    # Using within job
    - name: Use Config
      run: |
        echo ${{ steps.configuration.outputs.someconfig }}

  reuseconfig:
    needs: readfromkeyvault
    name: Reuses the config value from previous job
    runs-on: self-hosted
    container: ${{ github.event.inputs.acrname }}.azurecr.io/agent:latest

    steps:
    # Using in other job
    - name: Use Config
      run: |
        echo ${{needs.readfromkeyvault.outputs.someconfig}}
